### ISSUE TITLE
ImportError: cannot import name InstallError

### ISSUE THREAD

**Issue by shenyingzxc** [MarcoG3/WhatsDump#1]
This is the error I get when I run python whatsdump.py --wa-phone +mynumber--wa-verify sms

**Comment by shenyingzxc** [comment]
I ran into problems when installing adb, so I installed it without m2crypto. Tried using the pure-python-adb library as well but ran into no adb found error. Help!

**Comment by MarcoG3** [comment]
Hello, did you run the following command to install all the library dependencies?

`pip install -r requirements.txt`

**Comment by shenyingzxc** [comment]
No I did not! I did it and it works now, thank you!!

**Comment by dougalscastro** [comment]
> Hello, did you run the following command to install all the library dependencies?
> 
> `pip install -r requirements.txt`

Python 2.7 not have PIP
