### ISSUE TITLE
Installing Error: Failed to find package extras;intel;Hardware_Accelerated_Execution_Manager

### ISSUE THREAD

**Issue by pcedenis** [MarcoG3/WhatsDump#11]
Hi.

First, thanks for your work. 

I feel encouraged to learn development. 

I'm trying to  use the program, but when i'm installing SDK, got the following output:

"[INFO] SDK tools directory already exists, skipping download & extraction...
[INFO] Updating SDK from manager...
[=======================================] 100% Computing updates...             
[INFO] Accepting SDK licenses..
All SDK package licenses accepted.======] 100% Computing updates...             

[INFO] Installing packages from SDK Manager...
Warning: Failed to find package extras;intel;Hardware_Accelerated_Execution_Manager
[ERROR] Could not install packages from SDK Managerting updates...              
[ERROR] Failed to install Android SDK"

How can I solve this problem? I'm using Ubuntu 19.04.

**Comment by MarcoG3** [comment]
Are you using a 64-bit version of Ubuntu?

**Comment by pcedenis** [comment]
Yes.

**Comment by pcedenis** [comment]
I will try to use other distribution. Debian 32b is downloaded e will be installed in a VM. Whats the ideal enviromment to use the script?

**Comment by MarcoG3** [comment]
You should not try this on a VM as the emulator would be really slow and/or almost non functional. I asked the version of your OS because I've googled your error and it looks like HAXM does not support Ubuntu x86 (32 bit version). I will try to investigate further. Can you run `./android-sdk/tools/bin/sdkmanager --list`?

**Comment by pcedenis** [comment]
I got the following:

Warning: Unknown argument --list?
Usage: 
  sdkmanager [--uninstall] [<common args>] [--package_file=<file>] [<packages>...]
  sdkmanager --update [<common args>]
  sdkmanager --list [<common args>]
  sdkmanager --licenses [<common args>]
  sdkmanager --version

With --install (optional), installs or updates packages.
    By default, the listed packages are installed or (if already installed)
    updated to the latest version.
With --uninstall, uninstall the listed packages.

    <package> is a sdk-style path (e.g. "build-tools;23.0.0" or
             "platforms;android-23").
    <package-file> is a text file where each line is a sdk-style path
                   of a package to install or uninstall.
    Multiple --package_file arguments may be specified in combination
    with explicit paths.

With --update, all installed packages are updated to the latest version.

With --list, all installed and available packages are printed out.

With --licenses, show and offer the option to accept licenses for all
     available packages that have not already been accepted.

With --version, prints the current version of sdkmanager.

Common Arguments:
    --sdk_root=<sdkRootPath>: Use the specified SDK root instead of the SDK 
                              containing this tool

    --channel=<channelId>: Include packages in channels up to <channelId>.
                           Common channels are:
                           0 (Stable), 1 (Beta), 2 (Dev), and 3 (Canary).

    --include_obsolete: With --list, show obsolete packages in the
                        package listing. With --update, update obsolete
                        packages as well as non-obsolete.

    --no_https: Force all connections to use http rather than https.

    --proxy=<http | socks>: Connect via a proxy of the given type.

    --proxy_host=<IP or DNS address>: IP or DNS address of the proxy to use.

    --proxy_port=<port #>: Proxy port to connect to.

    --verbose: Enable verbose output.

* If the env var REPO_OS_OVERRIDE is set to "windows",

**Comment by pcedenis** [comment]
I found this topic about in askubuntu.com:

https://askubuntu.com/questions/600727/replacement-for-haxm-on-ubuntu-says-intel-x86-emulator-accelerator-is-not-comp

Maybe works, but I don't know how to modify your code to use KVM.

**Comment by MarcoG3** [comment]
Based on `sdkmanager --list` output looks like your hardware does not support HW acceleration. To be sure of this, can you paste the output of `egrep -c '(vmx|svm)' /proc/cpuinfo`?

**Comment by pcedenis** [comment]
The output was "4".

**Comment by MarcoG3** [comment]
Output of `$WHATSDUMP_LOCATION/android-sdk/emulator -accel-check`? Looks like you support KVM but not HAXM.

**Comment by pcedenis** [comment]
È Vero. Support just KVM. I'm now in a Windows Station and I'll try.

**Comment by RIPASSAS** [comment]
I removed the package "extras;intel;Hardware_Accelerated_Execution_Manager" from the src/android_sdk.py in the line 56 and it worked

**Comment by MarcoG3** [comment]
That's great to hear. I will soon update code to check if machine supports HAXM or KVM and add/remove the flag.

**Comment by pcedenis** [comment]
That's great to hear, too.

**Comment by MarcoG3** [comment]
Should be fixed in #2dd7f85

**Comment by pcedenis** [comment]
Wonderful. I will try it today and report the results.

**Comment by pcedenis** [comment]
I'm happy, works for me. Great. Sometimes occurs that error reported in other issue, of 3rd party library. But re-executing it works.
