### ISSUE TITLE
error --install-sdk

### ISSUE THREAD

**Issue by thiagozon** [MarcoG3/WhatsDump#15]
I have this error when i play : "python whatsdump.py --install-sdk"

"Traceback (most recent call last):
  File "whatsdump.py", line 5, in <module>
    import phonenumbers
ImportError: No module named phonenumbers"

May u help me?

Win10 x64
JDK 12.0.1 x64
Python 2.7.16 x86

**Comment by MarcoG3** [comment]
Take a look at issue #1 or you could use static binaries here: https://github.com/MarcoG3/WhatsDump/releases

**Comment by Acimaz** [comment]
I do have the same error and have installed all requirements. The executable doesnt work for me because it tells me that it cant find the whatsdump avd.

**Comment by Acimaz** [comment]
Hm reinstalling the phonenumbers package manually with pip and the same version like the one in the requirements.txt and then calling whatsdump.py with "python whatsdump.py --install-sdk" instead of just "whatsdump.py ..." worked for me now.
