### ISSUE TITLE
Beginner Guide!

### ISSUE THREAD

**Issue by Verraeter-DerKafkaeske** [MarcoG3/WhatsDump#16]
Hello!

I really appreciate your effort for this tool! But will there a somewhat more user-friendly Version in the future? :D I've never programmed myself, nor heard about or worked with "python"  so it's quite a challenge for me to use your tool

**Comment by MarcoG3** [comment]
Take a look at releases https://github.com/MarcoG3/WhatsDump/releases

Just download the binary for your OS and use it via command line, it is simple as it sounds! Unfortunately there are no plans to make a GUI of WhatsDump at the moment.
