### ISSUE TITLE
Stuck on retrieving messages from db

### ISSUE THREAD

**Issue by ItzSiL3Nce** [MarcoG3/WhatsDump#20]
It seems that the program remains stuck while retrieving files from the msgstore.db
I think It may be caused by the fact that WhatsApp recently released a new version and the old one (the one that currently is installed on the emulator) is deprecated. (In fact the app refuses to launch correctly)

**Comment by MarcoG3** [comment]
Can you give more informations about this issue?

**Comment by MarcoG3** [comment]
Fixed in 0f22740
