### ISSUE TITLE
Exception while installing whatsapp in the emulator

### ISSUE THREAD

**Issue by yadkee** [MarcoG3/WhatsDump#22]
[DEBUG] Emulator boot process completed
[INFO] Do not interact with the emulator!
[INFO] Trying to register phone on emulator... (may take few minutes)
[INFO] Installing WhatsApp...
[INFO] Cleaning WhatsApp...
[INFO] Moving extracted database into emulator...
[INFO] Touching "OK" at custom ROM alert...
[INFO] Agreeing to EULA...
[ERROR] Exception in verification: Can not allow WhatsApp to access media/files

After this error it just freezes here. I ran this with the --show-emulator flag and the window it is stuck on is this one:
![image](https://user-images.githubusercontent.com/31708119/61837389-d1c86c80-ae84-11e9-8688-af75d46a1014.png)

The fact that the pop-up appeared might be the reason why it can not accept the EULA. How could I get around this?
Manually clicking OK and trying to accept EULA ends up in the same window.
Adding some breakpoints gives us the following information:
_allow_access returned False after continue_view was False (line 313 of src/whatsapp.py)

Side note: I'm so happy that someone is finally providing a solution to get the whatsapp cryptkey after the android update broke the existing solutions. I love my whatsapp database and I'm hoping I can see the newest version using your program. Thank you!

**Comment by MarcoG3** [comment]
This looks weird because by default it should be enabled. Try to go on emulator settings (in the dropdown menu on the right) and try to find some setting related to cellular data and enable it. Let me know if you fix that.

**Comment by Acimaz** [comment]
![Bug](https://user-images.githubusercontent.com/3418387/62042432-6113ae00-b1fe-11e9-8141-3c74ea9958e6.PNG)

This is how it looks for me.

**Comment by Acimaz** [comment]
Clicking on the download button results in this page:

![image](https://user-images.githubusercontent.com/3418387/62042492-830d3080-b1fe-11e9-9e51-7f9c04ed4bc4.png)

**Comment by Acimaz** [comment]
Looks like we need a new version of the APK. I tried replacing it with this apk here https://apkpure.com/de/whatsapp-messenger/com.whatsapp but it didnt work.

`[ERROR] Exception in verification: /data/local/tmp/WhatsApp.apk could not be installed - [[INSTALL_FAILED_NO_MATCHING_AB]S]`

**Comment by MarcoG3** [comment]
You've probably picked the wrong APK from the site, emulator runs on x86 not on ARM. I'll do couple tests and update it.

**Comment by MarcoG3** [comment]
Should be fixed in 0f22740, let me know if you have any other issues
