### ISSUE TITLE
Problems after Whatsapp update, even after updating whatsdump 

### ISSUE THREAD

**Issue by pcedenis** [MarcoG3/WhatsDump#27]
After the WhatsApp update, I download the program again, but even then it doesn't work.
The program stop when show the INFO "touching and changing country code TextEdit". I has use the flag --show-emulator and I have verified that it does not really apply commands to the emulator when it arrives at this time. 

Does anyone else face the same problem?

My OS is Ubuntu 19.04 64 bits and prior to the WhatsApp upgrade it worked fine.

**Comment by felipesolari** [comment]
I have recently download and test, with --show-emulator, and it seems Whatsapp changed the process after verifying the sms code; there is no restore-button as I can see. 
Is it some work in the automation script that can be done to overcome this?

**Comment by pcedenis** [comment]
To me, the program stop before the sms code verify.

**Comment by pcedenis** [comment]
Problem solved. I deleted all files, downloaded again, reinstalled the dependencies and it worked.
