### ISSUE TITLE
Default partition size of 2048MB is too big

### ISSUE THREAD

**Issue by pseudobacon** [MarcoG3/WhatsDump#3]
![image](https://user-images.githubusercontent.com/12183854/57305290-25e47000-7124-11e9-8c87-381b9b0a2aae.png)

Maximum is 2047

**Comment by MarcoG3** [comment]
This is unfortunate, I didn't get that error after I changed partition size to 2048. Anyway, this is fixed in f37e95e, thanks for letting me know :)
