### ISSUE TITLE
Emulator does not recognise restore button after messages are restored

### ISSUE THREAD

**Issue by pseudobacon** [MarcoG3/WhatsDump#4]
![image](https://user-images.githubusercontent.com/12183854/57307676-56c6a400-7128-11e9-90e8-40fe8acc08f4.png)
My messages were restored, but the script doesn't recognise that the Restore button was available. I tried manually pressing it but it didn't continue the script

**Comment by MarcoG3** [comment]
Can you paste the complete output with `--verbose` flag?

**Comment by MarcoG3** [comment]
Can you still interact with emulator manually? That critical error message regarding the emulator could be the culprit.

**Comment by pseudobacon** [comment]
That happened after I tried pressing the Restore button. Will try again with verbose, need to trigger a call now haha

**Comment by MarcoG3** [comment]
Did restore process take longer than 5 minutes? It could be a timeout issue (once again)

**Comment by pseudobacon** [comment]
Hmm I think it might have. My emulator must run much slower on my setup than your machine, or I must have heaps more messages than what you tested with

**Comment by MarcoG3** [comment]
Increased restore waiting timeout to 15 minutes in bd1f02, let me know if you still encounter the same issue.

**Comment by pseudobacon** [comment]
Worked that time. Nice

![image](https://user-images.githubusercontent.com/12183854/57309748-f33e7580-712b-11e9-8ed7-980a9e3dec4f.png)

**Comment by MarcoG3** [comment]
Glad it worked! You extracted far more messages than me, that's why it took a little bit more to restore them all.
