### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by svsagar85** [MarcoG3/WhatsDump#6]
Hi
I have tried to run whatsdump and stuck at this error..
I am a complete noob....so please excuse my ignorance!

E:\Product pics\WhatsDump-master\WhatsDump-master>python whatsdump.py --wa-phone +mymobnumber --wa-verify sms

  File "whatsdump.py", line 228
    except WaException, e:
                      ^
SyntaxError: invalid syntax

**Comment by MarcoG3** [comment]
No worries! This is due to the version of `python` you're using. As stated in readme file, you must use Python 2.7.x to run WhatsDump. To check the version you're currently using, issue the following command:

`python -V`

You are probably running 3.x
