### ISSUE TITLE
ERROR Could not find/extract msgstore database from device (is Whatsapp installed?)

### ISSUE THREAD

**Issue by tapsy0** [MarcoG3/WhatsDump#9]
Hi,

I've got the following Error msg:
[INFO] Extracting msgstore.db.crypt from phone to output/[mynumber]/ ...
[INFO] Extracting msgstore database from path: ls: Unknown option '-t'. Aborting.
[INFO] Extracting msgstore database from path: ls: Unknown option '-t'. Aborting.
[ERROR] Could not find/extract msgstore database from device (is WhatsApp installed?)

WhatsApp is installed. At this stage should there be an emulator window opened? My antivirus program notificated me that adb got blocked but I've added it to the white list. Could there be a problem because of this?

Thanks in advance,
Chris

**Comment by MarcoG3** [comment]
Hello, I would try deleting `android-sdk/` directory, whitelisting WhatsDump directory and installing the SDK again by running it with `--install-sdk`. This is a pretty weird error which could be caused by AV messing things up.
